services:
  - type: web
    name: crccf-resume-builder-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: TIME_LIMIT_MINUTES
        value: 20
      - key: ADMIN_KEY
        value: admin123
      - key: MONGO_URI
        value: mongodb+srv://Aryaman007:aryaman143@cluster0.cxo50zl.mongodb.net/resume_builder
      - key: CORS_ORIGIN
        value: https://resume-builder-os-omms-projects.vercel.app,https://resume-builder-xi-gilt.vercel.app
    healthCheckPath: /health
    autoDeploy: true
    
databases:
  - name: crccf-resume-db
    plan: free
